import fs from 'node:fs';
import path from 'node:path';

/**
 * @param {string} directory
 * @returns {string[]}
 */
function getFolders(directory) {
	try {
		return fs.readdirSync(directory).filter((file) => fs.statSync(path.join(directory, file)).isDirectory());
	} catch (error) {
		console.error('Error reading directory:', error);
		return [];
	}
}

/**
 * @param {string} directory
 * @param {string} filename
 * @returns {string|null}
 */
function getFile(directory, filename) {
	const filePath = path.join(directory, filename);
	if (fs.existsSync(filePath)) {
		return fs.readFileSync(filePath, 'utf-8');
	}
	return null;
}

/**
 * Turns a component folder name into a valid, unique JS identifier.
 * e.g. "auto-suggest-box" -> "autoSuggestBox"
 * @param {string} folder
 * @returns {string}
 */
function toIdentifier(folder) {
	const camel = folder.replace(/[-_]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));
	const safe = camel.replace(/[^a-zA-Z0-9_$]/g, '');
	return /^[a-zA-Z_$]/.test(safe) ? safe : `_${safe}`;
}

const libPath = path.join('src/lib/components');
const sitePath = path.join('src/site/documentation');
const outFile = 'index.js';

/**
 * Generates the documentation index file.
 *
 * Scans every component under `src/lib/components` and, for those that expose a
 * `docs/index.ts`, imports its exported `META` constant. The generated module
 * re-exports every `META` as a single array, consumed by the docs layout to build
 * the navigation (and reusable anywhere the component metadata is needed).
 */
function generateComponentIndex() {
	const folders = getFolders(libPath)
		.filter((folder) => fs.existsSync(path.join(libPath, folder, 'docs', 'index.ts')))
		.sort();

	const seen = new Set();
	const entries = folders.map((folder) => {
		let id = toIdentifier(folder);
		// Guard against collisions after sanitising.
		while (seen.has(id)) id = `${id}_`;
		seen.add(id);
		return { folder, id };
	});

	const imports = entries.map(({ folder, id }) => `import { META as ${id} } from '$components/${folder}/docs/index.js';`);
	const list = entries.map(({ id }) => `\t${id}`).join(',\n');

	const output =
		`// AUTO-GENERATED by scripts/gen-urls.js — do not edit by hand.\n` +
		`// Run \`pnpm urls\` to regenerate.\n\n` +
		`${imports.join('\n')}\n\n` +
		`/** @type {import('$types').Meta[]} */\n` +
		`export default [\n${list}\n];\n`;

	if (!fs.existsSync(sitePath)) {
		fs.mkdirSync(sitePath, { recursive: true });
	}

	const currentFile = getFile(sitePath, outFile);
	if (currentFile === output) {
		console.info('No changes detected. Skipping file write.');
		return;
	}

	fs.writeFileSync(path.join(sitePath, outFile), output, 'utf-8');
	console.info(`Wrote ${entries.length} component(s) to ${path.join(sitePath, outFile)}.`);
}

generateComponentIndex();
